### PR TITLE
Port Halremote to Machinetalk GSL

### PR DESCRIPTION
**Pull request by machinekoder**
This patch ports Pymachinetalk to the generated Machientalk GSL bindings.

@luminize please let me know if this works for you

### CODE REVIEW

**Comment by luminize** [comment]
I follow your setup instructions and get:
```bash
machinekit@xw6600:~/pymachinetalk$ sudo pip install machinetalk-protobuf fysom
Downloading/unpacking machinetalk-protobuf
  Could not find any downloads that satisfy the requirement machinetalk-protobuf
Cleaning up...
```
my apt repositories should be ok, note during apt update:
```
Get:16 http://deb.machinekit.io jessie InRelease [3,357 B]                   
Get:17 http://deb.machinekit.io jessie/main amd64 Packages [9,992 B]         
```

**Comment by luminize** [comment]
but due to my RIP install this does not prevent me to `sudo python setup.py install`

**Comment by machinekoder** [comment]
now it should work

**Comment by luminize** [comment]
I've ran the examples/basic/anddemo.py and that works as expected. So I'll merge now

**Comment by luminize** [comment]
If somebody gives me rights to do so that is :)

**Comment by machinekoder** [comment]
@ArcEye Can you please add the machinekit/maintainers group to the project.

**Comment by ArcEye** [comment]
I have added Administrators and Maintainers with read / write access, so everyone in the teams should be able to merge now

**Pull request merged**
