### PR TITLE
README.md: add python-avahi install instruction

### PR DESCRIPTION
**Pull request by luminize**

### CODE REVIEW

**Comment by machinekoder** [comment]
@luminize Pymachinetalk does not depend on python-avahi anymore. Is there any reference in the source code left?

**Comment by luminize** [comment]
> On 26 May 2017, at 16:15, Alexander Rössler <notifications@github.com> wrote:
> 
> @luminize Pymachinetalk does not depend on python-avahi anymore. Is there any reference in the source code left?
> 
sudo pip install pymachinetalk on a vanilla debian install wouldn't let me run my code without apt installing python-avahi. My code was based on you develop branch.
Have to look if I can find the reference.

**Comment by luminize** [comment]
this was the error
```
starting configserver... Traceback (most recent call last):
  File "/home/machinekit/machinekit/bin/configserver", line 12, in <module>
    from machinekit import service
  File "/home/machinekit/machinekit/lib/python/machinekit/service.py", line 1, in <module>
    import avahi
ImportError: No module named avahi
```
Looking at this a second time, this seems to be the machinekit configserver

**Comment by machinekoder** [comment]
ah, yes
Isn't there a dependency in the Machinekit package?

**Comment by luminize** [comment]
apparently not. I'll close this PR

**Comment by machinekoder** [comment]
Should be easy to fix.
I think there is already an issue in the Machinekit issue tracker if I remember correctly.

**Pull request closed without merging**
